name: tp_flutter_downloader
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  bloc: ^8.1.4
  logger: ^2.5.0
  html: ^0.15.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  auto_route: ^9.2.2
  collection: ^1.19.0
  path_provider: ^2.1.5
  video_player: ^2.9.2
  yaml: ^3.1.3
  pretty_dio_logger: ^1.4.0
  dotted_border: ^2.1.0
  image_gallery_saver_plus: ^3.0.5
  shimmer: ^3.0.0
  tuple: ^2.0.2
  audio_waveforms: ^1.2.0
  permission_handler: ^11.3.1
  path: ^1.9.0
  ffmpeg_kit_flutter: ^6.0.3
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  share_plus: ^10.1.4
  social_share:
    path: ./social_share
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18
  firebase_core: ^3.12.1
  firebase_remote_config: ^5.4.2
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  auto_route_generator: ^9.0.0
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.9.0
  drift_dev: ^2.26.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: TTNormsPro
      fonts:
        - asset: assets/fonts/TT Norms Pro Regular.otf
        - asset: assets/fonts/TT Norms Pro Bold.otf
          weight: 700
        - asset: assets/fonts/TT Norms Pro Medium.otf
          weight: 500
        - asset: assets/fonts/TT Norms Pro Light.otf
          weight: 300
        - asset: assets/fonts/TT Norms Pro Italic.otf
          style: italic
        - asset: assets/fonts/TT Norms Pro Bold Italic.otf
          weight: 700
          style: italic
